# docker-compose.prod.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=testdeconnection.onrender.com,localhost
      - DATABASE_URL=postgresql://postgres:xxxxx@db.xxxxx.supabase.co:5432/postgres?sslmode=require
      - SECRET_KEY=django-insecure-key

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000"
    environment:
      - VITE_API_URL=http://backend:8000/api